_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.8.19
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 13
                - 23
                - 55
            "4": 3.8.19
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
